# Generated by Django 4.2.5 on 2023-10-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sales_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="Product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sales_app.products"
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="Staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sales_app.staffs"
            ),
        ),
    ]
