# Generated by Django 4.2.5 on 2023-11-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales_app", "0002_alter_sales_product_alter_sales_staff"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sales",
            table="Sale",
        ),
    ]
